//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 护土精灵 {
            get {
                return ((global::System.DateTime)(this["护土精灵"]));
            }
            set {
                this["护土精灵"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3900")]
        public int 护土精灵CD {
            get {
                return ((int)(this["护土精灵CD"]));
            }
            set {
                this["护土精灵CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 丑男子沃迦加 {
            get {
                return ((global::System.DateTime)(this["丑男子沃迦加"]));
            }
            set {
                this["丑男子沃迦加"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 丑男子沃迦加CD {
            get {
                return ((int)(this["丑男子沃迦加CD"]));
            }
            set {
                this["丑男子沃迦加CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 伽洛克 {
            get {
                return ((global::System.DateTime)(this["伽洛克"]));
            }
            set {
                this["伽洛克"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2460")]
        public int 伽洛克CD {
            get {
                return ((int)(this["伽洛克CD"]));
            }
            set {
                this["伽洛克CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 魔导地狱爪 {
            get {
                return ((global::System.DateTime)(this["魔导地狱爪"]));
            }
            set {
                this["魔导地狱爪"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 魔导地狱爪CD {
            get {
                return ((int)(this["魔导地狱爪CD"]));
            }
            set {
                this["魔导地狱爪CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 火愤牛 {
            get {
                return ((global::System.DateTime)(this["火愤牛"]));
            }
            set {
                this["火愤牛"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3900")]
        public int 火愤牛CD {
            get {
                return ((int)(this["火愤牛CD"]));
            }
            set {
                this["火愤牛CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 纳恩 {
            get {
                return ((global::System.DateTime)(this["纳恩"]));
            }
            set {
                this["纳恩"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 纳恩CD {
            get {
                return ((int)(this["纳恩CD"]));
            }
            set {
                this["纳恩CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 咕尔呱洛斯 {
            get {
                return ((global::System.DateTime)(this["咕尔呱洛斯"]));
            }
            set {
                this["咕尔呱洛斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4480")]
        public int 咕尔呱洛斯CD {
            get {
                return ((int)(this["咕尔呱洛斯CD"]));
            }
            set {
                this["咕尔呱洛斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 乌克提希 {
            get {
                return ((global::System.DateTime)(this["乌克提希"]));
            }
            set {
                this["乌克提希"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 乌克提希CD {
            get {
                return ((int)(this["乌克提希CD"]));
            }
            set {
                this["乌克提希CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 牛头黑神 {
            get {
                return ((global::System.DateTime)(this["牛头黑神"]));
            }
            set {
                this["牛头黑神"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3900")]
        public int 牛头黑神CD {
            get {
                return ((int)(this["牛头黑神CD"]));
            }
            set {
                this["牛头黑神CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 角祖 {
            get {
                return ((global::System.DateTime)(this["角祖"]));
            }
            set {
                this["角祖"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 角祖CD {
            get {
                return ((int)(this["角祖CD"]));
            }
            set {
                this["角祖CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 南迪 {
            get {
                return ((global::System.DateTime)(this["南迪"]));
            }
            set {
                this["南迪"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2820")]
        public int 南迪CD {
            get {
                return ((int)(this["南迪CD"]));
            }
            set {
                this["南迪CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 玛贝利 {
            get {
                return ((global::System.DateTime)(this["玛贝利"]));
            }
            set {
                this["玛贝利"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int 玛贝利CD {
            get {
                return ((int)(this["玛贝利CD"]));
            }
            set {
                this["玛贝利CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 乌尔伽鲁 {
            get {
                return ((global::System.DateTime)(this["乌尔伽鲁"]));
            }
            set {
                this["乌尔伽鲁"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3960")]
        public int 乌尔伽鲁CD {
            get {
                return ((int)(this["乌尔伽鲁CD"]));
            }
            set {
                this["乌尔伽鲁CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 千眼凝胶 {
            get {
                return ((global::System.DateTime)(this["千眼凝胶"]));
            }
            set {
                this["千眼凝胶"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int 千眼凝胶CD {
            get {
                return ((int)(this["千眼凝胶CD"]));
            }
            set {
                this["千眼凝胶CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 夺心魔 {
            get {
                return ((global::System.DateTime)(this["夺心魔"]));
            }
            set {
                this["夺心魔"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4480")]
        public int 夺心魔CD {
            get {
                return ((int)(this["夺心魔CD"]));
            }
            set {
                this["夺心魔CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 盖得 {
            get {
                return ((global::System.DateTime)(this["盖得"]));
            }
            set {
                this["盖得"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 盖得CD {
            get {
                return ((int)(this["盖得CD"]));
            }
            set {
                this["盖得CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 千竿口花希达 {
            get {
                return ((global::System.DateTime)(this["千竿口花希达"]));
            }
            set {
                this["千竿口花希达"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3480")]
        public int 千竿口花希达CD {
            get {
                return ((int)(this["千竿口花希达CD"]));
            }
            set {
                this["千竿口花希达CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 尾宿蛛蝎 {
            get {
                return ((global::System.DateTime)(this["尾宿蛛蝎"]));
            }
            set {
                this["尾宿蛛蝎"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225")]
        public int 尾宿蛛蝎CD {
            get {
                return ((int)(this["尾宿蛛蝎CD"]));
            }
            set {
                this["尾宿蛛蝎CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 雷德罗巨蛇 {
            get {
                return ((global::System.DateTime)(this["雷德罗巨蛇"]));
            }
            set {
                this["雷德罗巨蛇"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2520")]
        public int 雷德罗巨蛇CD {
            get {
                return ((int)(this["雷德罗巨蛇CD"]));
            }
            set {
                this["雷德罗巨蛇CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 弗内乌斯 {
            get {
                return ((global::System.DateTime)(this["弗内乌斯"]));
            }
            set {
                this["弗内乌斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int 弗内乌斯CD {
            get {
                return ((int)(this["弗内乌斯CD"]));
            }
            set {
                this["弗内乌斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 巴拉乌尔 {
            get {
                return ((global::System.DateTime)(this["巴拉乌尔"]));
            }
            set {
                this["巴拉乌尔"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3960")]
        public int 巴拉乌尔CD {
            get {
                return ((int)(this["巴拉乌尔CD"]));
            }
            set {
                this["巴拉乌尔CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 玛赫斯 {
            get {
                return ((global::System.DateTime)(this["玛赫斯"]));
            }
            set {
                this["玛赫斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int 玛赫斯CD {
            get {
                return ((int)(this["玛赫斯CD"]));
            }
            set {
                this["玛赫斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 虚无探索者 {
            get {
                return ((global::System.DateTime)(this["虚无探索者"]));
            }
            set {
                this["虚无探索者"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3480")]
        public int 虚无探索者CD {
            get {
                return ((int)(this["虚无探索者CD"]));
            }
            set {
                this["虚无探索者CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 阿列刻特利昂 {
            get {
                return ((global::System.DateTime)(this["阿列刻特利昂"]));
            }
            set {
                this["阿列刻特利昂"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 阿列刻特利昂CD {
            get {
                return ((int)(this["阿列刻特利昂CD"]));
            }
            set {
                this["阿列刻特利昂CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 努纽努维 {
            get {
                return ((global::System.DateTime)(this["努纽努维"]));
            }
            set {
                this["努纽努维"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2640")]
        public int 努纽努维CD {
            get {
                return ((int)(this["努纽努维CD"]));
            }
            set {
                this["努纽努维CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 札尼戈 {
            get {
                return ((global::System.DateTime)(this["札尼戈"]));
            }
            set {
                this["札尼戈"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 札尼戈CD {
            get {
                return ((int)(this["札尼戈CD"]));
            }
            set {
                this["札尼戈CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 蚓螈巨虫 {
            get {
                return ((global::System.DateTime)(this["蚓螈巨虫"]));
            }
            set {
                this["蚓螈巨虫"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3480")]
        public int 蚓螈巨虫CD {
            get {
                return ((int)(this["蚓螈巨虫CD"]));
            }
            set {
                this["蚓螈巨虫CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 菲兰德的遗火 {
            get {
                return ((global::System.DateTime)(this["菲兰德的遗火"]));
            }
            set {
                this["菲兰德的遗火"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 菲兰德的遗火CD {
            get {
                return ((int)(this["菲兰德的遗火CD"]));
            }
            set {
                this["菲兰德的遗火CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 布隆特斯 {
            get {
                return ((global::System.DateTime)(this["布隆特斯"]));
            }
            set {
                this["布隆特斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3840")]
        public int 布隆特斯CD {
            get {
                return ((int)(this["布隆特斯CD"]));
            }
            set {
                this["布隆特斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 花舞仙人刺 {
            get {
                return ((global::System.DateTime)(this["花舞仙人刺"]));
            }
            set {
                this["花舞仙人刺"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 花舞仙人刺CD {
            get {
                return ((int)(this["花舞仙人刺CD"]));
            }
            set {
                this["花舞仙人刺CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 萨法特 {
            get {
                return ((global::System.DateTime)(this["萨法特"]));
            }
            set {
                this["萨法特"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int 萨法特CD {
            get {
                return ((int)(this["萨法特CD"]));
            }
            set {
                this["萨法特CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 马拉克 {
            get {
                return ((global::System.DateTime)(this["马拉克"]));
            }
            set {
                this["马拉克"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int 马拉克CD {
            get {
                return ((int)(this["马拉克CD"]));
            }
            set {
                this["马拉克CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 阿格里帕 {
            get {
                return ((global::System.DateTime)(this["阿格里帕"]));
            }
            set {
                this["阿格里帕"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int 阿格里帕CD {
            get {
                return ((int)(this["阿格里帕CD"]));
            }
            set {
                this["阿格里帕CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 库雷亚 {
            get {
                return ((global::System.DateTime)(this["库雷亚"]));
            }
            set {
                this["库雷亚"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int 库雷亚CD {
            get {
                return ((int)(this["库雷亚CD"]));
            }
            set {
                this["库雷亚CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int ACD {
            get {
                return ((int)(this["ACD"]));
            }
            set {
                this["ACD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int fourSCD {
            get {
                return ((int)(this["fourSCD"]));
            }
            set {
                this["fourSCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 凯撒贝希摩斯 {
            get {
                return ((global::System.DateTime)(this["凯撒贝希摩斯"]));
            }
            set {
                this["凯撒贝希摩斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 神穆尔鸟 {
            get {
                return ((global::System.DateTime)(this["神穆尔鸟"]));
            }
            set {
                this["神穆尔鸟"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 苍白骑士 {
            get {
                return ((global::System.DateTime)(this["苍白骑士"]));
            }
            set {
                this["苍白骑士"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 刚德瑞瓦 {
            get {
                return ((global::System.DateTime)(this["刚德瑞瓦"]));
            }
            set {
                this["刚德瑞瓦"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 极乐鸟 {
            get {
                return ((global::System.DateTime)(this["极乐鸟"]));
            }
            set {
                this["极乐鸟"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 卢克洛塔 {
            get {
                return ((global::System.DateTime)(this["卢克洛塔"]));
            }
            set {
                this["卢克洛塔"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 米勒卡 {
            get {
                return ((global::System.DateTime)(this["米勒卡"]));
            }
            set {
                this["米勒卡"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 卢芭 {
            get {
                return ((global::System.DateTime)(this["卢芭"]));
            }
            set {
                this["卢芭"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 双足飞龙之王 {
            get {
                return ((global::System.DateTime)(this["双足飞龙之王"]));
            }
            set {
                this["双足飞龙之王"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 派拉斯特暴龙 {
            get {
                return ((global::System.DateTime)(this["派拉斯特暴龙"]));
            }
            set {
                this["派拉斯特暴龙"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 斯特拉斯 {
            get {
                return ((global::System.DateTime)(this["斯特拉斯"]));
            }
            set {
                this["斯特拉斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 机工兵斯利普金克斯 {
            get {
                return ((global::System.DateTime)(this["机工兵斯利普金克斯"]));
            }
            set {
                this["机工兵斯利普金克斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 布涅 {
            get {
                return ((global::System.DateTime)(this["布涅"]));
            }
            set {
                this["布涅"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 阿伽托斯 {
            get {
                return ((global::System.DateTime)(this["阿伽托斯"]));
            }
            set {
                this["阿伽托斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 西斯尤 {
            get {
                return ((global::System.DateTime)(this["西斯尤"]));
            }
            set {
                this["西斯尤"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 恩克拉多斯 {
            get {
                return ((global::System.DateTime)(this["恩克拉多斯"]));
            }
            set {
                this["恩克拉多斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 坎帕提 {
            get {
                return ((global::System.DateTime)(this["坎帕提"]));
            }
            set {
                this["坎帕提"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 恶臭狂花 {
            get {
                return ((global::System.DateTime)(this["恶臭狂花"]));
            }
            set {
                this["恶臭狂花"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 优昙婆罗花 {
            get {
                return ((global::System.DateTime)(this["优昙婆罗花"]));
            }
            set {
                this["优昙婆罗花"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 爬骨怪龙 {
            get {
                return ((global::System.DateTime)(this["爬骨怪龙"]));
            }
            set {
                this["爬骨怪龙"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 盐和光 {
            get {
                return ((global::System.DateTime)(this["盐和光"]));
            }
            set {
                this["盐和光"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 巨大鳐 {
            get {
                return ((global::System.DateTime)(this["巨大鳐"]));
            }
            set {
                this["巨大鳐"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 兀鲁忽乃朝鲁 {
            get {
                return ((global::System.DateTime)(this["兀鲁忽乃朝鲁"]));
            }
            set {
                this["兀鲁忽乃朝鲁"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 伽马 {
            get {
                return ((global::System.DateTime)(this["伽马"]));
            }
            set {
                this["伽马"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 女王蜂 {
            get {
                return ((global::System.DateTime)(this["女王蜂"]));
            }
            set {
                this["女王蜂"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 奥迦斯 {
            get {
                return ((global::System.DateTime)(this["奥迦斯"]));
            }
            set {
                this["奥迦斯"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 熔骨炎蝎 {
            get {
                return ((global::System.DateTime)(this["熔骨炎蝎"]));
            }
            set {
                this["熔骨炎蝎"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 弗克施泰因 {
            get {
                return ((global::System.DateTime)(this["弗克施泰因"]));
            }
            set {
                this["弗克施泰因"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 马希沙 {
            get {
                return ((global::System.DateTime)(this["马希沙"]));
            }
            set {
                this["马希沙"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 泛光晶体 {
            get {
                return ((global::System.DateTime)(this["泛光晶体"]));
            }
            set {
                this["泛光晶体"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 船幽灵 {
            get {
                return ((global::System.DateTime)(this["船幽灵"]));
            }
            set {
                this["船幽灵"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 鬼观梦 {
            get {
                return ((global::System.DateTime)(this["鬼观梦"]));
            }
            set {
                this["鬼观梦"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 硕姆 {
            get {
                return ((global::System.DateTime)(this["硕姆"]));
            }
            set {
                this["硕姆"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 基里麦卡拉 {
            get {
                return ((global::System.DateTime)(this["基里麦卡拉"]));
            }
            set {
                this["基里麦卡拉"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 安迦达 {
            get {
                return ((global::System.DateTime)(this["安迦达"]));
            }
            set {
                this["安迦达"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime 象魔修罗 {
            get {
                return ((global::System.DateTime)(this["象魔修罗"]));
            }
            set {
                this["象魔修罗"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5520")]
        public int 卢克洛塔CD {
            get {
                return ((int)(this["卢克洛塔CD"]));
            }
            set {
                this["卢克洛塔CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5520")]
        public int 神穆尔鸟CD {
            get {
                return ((int)(this["神穆尔鸟CD"]));
            }
            set {
                this["神穆尔鸟CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5340")]
        public int 刚德瑞瓦CD {
            get {
                return ((int)(this["刚德瑞瓦CD"]));
            }
            set {
                this["刚德瑞瓦CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 凯撒贝希摩斯CD {
            get {
                return ((int)(this["凯撒贝希摩斯CD"]));
            }
            set {
                this["凯撒贝希摩斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 极乐鸟CD {
            get {
                return ((int)(this["极乐鸟CD"]));
            }
            set {
                this["极乐鸟CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 苍白骑士CD {
            get {
                return ((int)(this["苍白骑士CD"]));
            }
            set {
                this["苍白骑士CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 米勒卡CD {
            get {
                return ((int)(this["米勒卡CD"]));
            }
            set {
                this["米勒卡CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 卢芭CD {
            get {
                return ((int)(this["卢芭CD"]));
            }
            set {
                this["卢芭CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 双足飞龙之王CD {
            get {
                return ((int)(this["双足飞龙之王CD"]));
            }
            set {
                this["双足飞龙之王CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 派拉斯特暴龙CD {
            get {
                return ((int)(this["派拉斯特暴龙CD"]));
            }
            set {
                this["派拉斯特暴龙CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 斯特拉斯CD {
            get {
                return ((int)(this["斯特拉斯CD"]));
            }
            set {
                this["斯特拉斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 机工兵斯利普金克斯CD {
            get {
                return ((int)(this["机工兵斯利普金克斯CD"]));
            }
            set {
                this["机工兵斯利普金克斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 布涅CD {
            get {
                return ((int)(this["布涅CD"]));
            }
            set {
                this["布涅CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 阿伽托斯CD {
            get {
                return ((int)(this["阿伽托斯CD"]));
            }
            set {
                this["阿伽托斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 西斯尤CD {
            get {
                return ((int)(this["西斯尤CD"]));
            }
            set {
                this["西斯尤CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 恩克拉多斯CD {
            get {
                return ((int)(this["恩克拉多斯CD"]));
            }
            set {
                this["恩克拉多斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 坎帕提CD {
            get {
                return ((int)(this["坎帕提CD"]));
            }
            set {
                this["坎帕提CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 恶臭狂花CD {
            get {
                return ((int)(this["恶臭狂花CD"]));
            }
            set {
                this["恶臭狂花CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 优昙婆罗花CD {
            get {
                return ((int)(this["优昙婆罗花CD"]));
            }
            set {
                this["优昙婆罗花CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 爬骨怪龙CD {
            get {
                return ((int)(this["爬骨怪龙CD"]));
            }
            set {
                this["爬骨怪龙CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 盐和光CD {
            get {
                return ((int)(this["盐和光CD"]));
            }
            set {
                this["盐和光CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 巨大鳐CD {
            get {
                return ((int)(this["巨大鳐CD"]));
            }
            set {
                this["巨大鳐CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 兀鲁忽乃朝鲁CD {
            get {
                return ((int)(this["兀鲁忽乃朝鲁CD"]));
            }
            set {
                this["兀鲁忽乃朝鲁CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5100")]
        public int 伽马CD {
            get {
                return ((int)(this["伽马CD"]));
            }
            set {
                this["伽马CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 女王蜂CD {
            get {
                return ((int)(this["女王蜂CD"]));
            }
            set {
                this["女王蜂CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 奥迦斯CD {
            get {
                return ((int)(this["奥迦斯CD"]));
            }
            set {
                this["奥迦斯CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 熔骨炎蝎CD {
            get {
                return ((int)(this["熔骨炎蝎CD"]));
            }
            set {
                this["熔骨炎蝎CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 弗克施泰因CD {
            get {
                return ((int)(this["弗克施泰因CD"]));
            }
            set {
                this["弗克施泰因CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 马希沙CD {
            get {
                return ((int)(this["马希沙CD"]));
            }
            set {
                this["马希沙CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 泛光晶体CD {
            get {
                return ((int)(this["泛光晶体CD"]));
            }
            set {
                this["泛光晶体CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 船幽灵CD {
            get {
                return ((int)(this["船幽灵CD"]));
            }
            set {
                this["船幽灵CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 鬼观梦CD {
            get {
                return ((int)(this["鬼观梦CD"]));
            }
            set {
                this["鬼观梦CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 硕姆CD {
            get {
                return ((int)(this["硕姆CD"]));
            }
            set {
                this["硕姆CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 基里麦卡拉CD {
            get {
                return ((int)(this["基里麦卡拉CD"]));
            }
            set {
                this["基里麦卡拉CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 安迦达CD {
            get {
                return ((int)(this["安迦达CD"]));
            }
            set {
                this["安迦达CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int 象魔修罗CD {
            get {
                return ((int)(this["象魔修罗CD"]));
            }
            set {
                this["象魔修罗CD"] = value;
            }
        }
    }
}
